server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/auth/**

            - id: order-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/orders/**

            - id: processing-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/processing/**

            - id: notification-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/notifications/**

            - id: faas-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/functions/**

auth:
  service:
    url: http://localhost:8083

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://auth-service:8083
              predicates:
                - Path=/api/auth/**

            - id: order-service
              uri: http://order-service:8081
              predicates:
                - Path=/api/orders/**

            - id: processing-service
              uri: http://processing-service:8082
              predicates:
                - Path=/api/processing/**

            - id: notification-service
              uri: http://notification-service:8084
              predicates:
                - Path=/api/notifications/**

            - id: faas-service
              uri: http://faas-service:8085
              predicates:
                - Path=/api/functions/**

auth:
  service:
    url: http://auth-service:8083